apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: tier-app
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tier-app
      tier: backend
  template:
    metadata:
      labels:
        app: tier-app
        tier: backend
    spec:
      containers:
      - name: backend
        image: tier-app-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://myuser:mypassword@db-service:5432/tierapp"  # ⬅️ فيها password
        - name: NODE_ENV
          value: "production"
